# Generated by Django 5.1.5 on 2025-01-21 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_analysis', '0001_initial'),
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cosine_similarity', models.FloatField()),
                ('id_cv', models.ForeignKey(db_column='id_cv', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cv_analysis.cv')),
                ('id_offre', models.ForeignKey(db_column='id_offre', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='job_offers.joboffer')),
            ],
        ),
    ]
