# Generated by Django 5.1.5 on 2025-01-21 15:48

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id_cv', models.UUIDField(db_column='id_cv', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_insertion', models.DateField()),
                ('cv_text', models.TextField(default='null')),
                ('cv_pretraite', models.TextField(default='null')),
                ('cv_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=1536)),
                ('competences', models.JSONField(default=dict)),
                ('experience', models.JSONField()),
                ('resume_cv', models.TextField()),
                ('commitment', models.CharField(blank=True, max_length=255, null=True)),
                ('disponibilite', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_salaire', models.IntegerField(default=0)),
                ('domaine_etude', models.CharField(blank=True, max_length=255, null=True)),
                ('langue', models.JSONField(default=dict)),
                ('candidat', models.ForeignKey(db_column='id_candidat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='users.candidat')),
            ],
            options={
                'db_table': 'cv_analysis',
            },
        ),
    ]
