# Generated by Django 5.1.4 on 2025-01-07 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0002_alter_cv_user'),
        ('users', '0004_alter_candidat_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.AddField(
            model_name='cv',
            name='candidat',
            field=models.ForeignKey(db_column='id_candidat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='users.candidat'),
        ),
        migrations.AddField(
            model_name='cv',
            name='commitment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_pretraite',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_vector',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='cv',
            name='disponibilite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='domaine_etude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='exp_salaire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='resume_cv',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='competences',
            field=models.JSONField(default='null'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='cv_text',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='date_insertion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='id_cv',
            field=models.UUIDField(db_column='id_cv', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='cv',
            table='cv_analysis',
        ),
    ]
