# Generated by Django 5.1.4 on 2024-12-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0003_remove_cv_cv_id_remove_cv_user_cv_candidat_and_more'),
        ('users', '0004_alter_candidat_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='candidat',
            field=models.ForeignKey(db_column='id_candidat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='users.candidat'),
        ),
    ]
