# Generated by Django 5.1.4 on 2025-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analysis', '0003_remove_cv_user_cv_candidat_cv_commitment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='competences',
            field=models.JSONField(default=dict),
        ),
    ]
