# Generated by Django 5.1.5 on 2025-01-21 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.UUIDField(db_column='id_entreprise', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('domaine', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('id_offre', models.ForeignKey(db_column='id_offre', on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='job_offers.joboffer')),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
    ]
