# Generated by Django 5.1.5 on 2025-01-21 15:46

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id_offre', models.UUIDField(db_column='id_offre', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_pretraite', models.TextField()),
                ('type_contrat', models.CharField(max_length=255)),
                ('revenu', models.IntegerField()),
                ('link_interview', models.TextField()),
                ('google_form', models.TextField()),
                ('kano', models.CharField(max_length=255)),
                ('cv_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=1536)),
            ],
            options={
                'db_table': 'offre',
            },
        ),
    ]
