# Generated by Django 5.1.4 on 2024-12-26 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_offre', models.TextField()),
                ('offre_societe', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'offre',
            },
        ),
    ]
