# Generated by Django 5.1.4 on 2024-12-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_offre'),
        ('similarity', '0002_alter_result_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobOffer',
        ),
    ]
