# Generated by Django 5.1.4 on 2024-12-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0004_joboffer'),
        ('similarity', '0003_alter_result_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offre',
        ),
    ]
