# Generated by Django 5.1.4 on 2025-01-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0005_delete_offre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='joboffer',
            table='offre',
        ),
    ]
