# Generated by Django 5.1.5 on 2025-01-21 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('numero_tlfn', models.CharField(blank=True, max_length=20, null=True)),
                ('profil', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'candidat',
            },
        ),
    ]
