# Generated by Django 5.1.4 on 2024-12-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_candidate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidat',
            table='candidat',
        ),
    ]
